[ODOO16]
URL = https://tu_instancia_o16.odoo.com
DB = nombre_base_datos_o16
USER = usuario_o16
PASS = contraseña_o16

[ODOO17]
URL = http://tu_instancia_o17.com:8069
DB = nombre_base_datos_o17
USER = usuario_o17
PASS = contraseña_o17

[SYNC_SETTINGS]
# Nombre del archivo CSV que contiene los códigos a sincronizar
CSV_FILENAME = products_to_sync.csv