[ODOO16]
URL = https://santabohemia.odoo.com
DB = odoo-mastercore-sb-master-7731718
USER = admin
PASS = Pass.root

[ODOO17]
URL = http://localhost:8069
DB = SantaCompleto02
#DB = Pos-4-ce
USER = admin
PASS = santa2024

[SYNC_SETTINGS]
# Define el nombre del archivo CSV 
CSV_FILENAME = products_to_sync.csv